# Generated by Django 5.0.6 on 2024-07-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('tamanio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FuenteAlimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltaje_in', models.FloatField()),
                ('voltaje_out', models.FloatField()),
                ('amperaje_in', models.FloatField()),
                ('amperaje_out', models.FloatField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(blank=True, choices=[('lineal', 'Lineal'), ('conmutada', 'Conmutada'), ('regulada', 'Regulada'), ('no_regulada', 'No Regulada'), ('dc', 'DC'), ('ac', 'AC'), ('bench', 'Bench'), ('atx', 'ATX')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoResidual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Protoboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanio', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Esp32Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPines', models.IntegerField()),
                ('fabricante', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('camara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.camara')),
            ],
        ),
        migrations.CreateModel(
            name='BrazoRobotico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dimensiones', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('material', models.CharField(max_length=100)),
                ('esp32_cam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.esp32cam')),
                ('fuente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.fuentealimentacion')),
                ('protoboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.protoboard')),
            ],
            options={
                'permissions': [('puede_crear_BrazoRobotico', 'Puede crear Brazo Robótico'), ('puede_editar_BrazoRobotico', 'Puede editar Brazo Robótico'), ('puede_borrar_BrazoRobotico', 'Puede borrar Brazo Robotico')],
            },
        ),
        migrations.CreateModel(
            name='EventoRecoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_recoleccion', models.DateField()),
                ('hora_recoleccion', models.CharField(max_length=100)),
                ('brazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.brazorobotico')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoPin', models.CharField(blank=True, choices=[('alimentacion', 'Alimentación'), ('entrada_digital', 'Entrada Digital'), ('salida_digital', 'Salida Digital'), ('comunicacion', 'Comunicación'), ('entrada_analogica', 'Entrada Analógica'), ('salida_analogica', 'Salida_Analógica'), ('de_camara', 'De Cámara'), ('programacion', 'Programación')], max_length=100)),
                ('esp32_cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.esp32cam')),
            ],
        ),
        migrations.CreateModel(
            name='Servo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('torque', models.FloatField()),
                ('potencia', models.FloatField()),
                ('ubicacion', models.CharField(blank=True, choices=[('pinza', 'Pinza'), ('codo', 'Codo'), ('base', 'Base'), ('antebrazo', 'Antebrazo')], max_length=100)),
                ('brazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionBrazoRobotico.brazorobotico')),
            ],
        ),
    ]
